### PR TITLE
Adding missing WF 17 and 18 in unit tests

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
I'm worried about the failed tests. Any idea ?

**Comment by odockal** [comment]
@jeffmaury I am trying locally, I am just getting some baseline check failure, will get rid of these and retest.

**Comment by odockal** [comment]
@jeffmaury Runtime version mismatch in test, see last commit. Middle commit has bump up versions that I was not able to build locally, but jenkins seemed not to have an issue..strange

**Comment by odockal** [comment]
@jeffmaury done.

**Comment by odockal** [comment]
Former unit test count: 3550, actual: 3743. So we got some missing unit tests at place, now.

**Comment by odockal** [comment]
@jeffmaury Is this good enough to merge? So we can rebase the other PR and rerun all tests against them?

**Comment by odockal** [comment]
@jeffmaury @jkopriva Objections to merge? If not, please merge this so we can use more unit tests. thanks

**Comment by odockal** [comment]
@jeffmaury Thanks!

**Pull request merged**
