### PR TITLE
Jbide 26598 fix jmx navigator local j vm with jdk9+everywhere improved withjbosstools common to modify too

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
requires https://github.com/jbosstools/jbosstools-base/pull/642

**Comment by robstryker** [comment]
When ignoring whitespace, this is a simple 4 line patch. Dead simple, very clean. +1. 

To be clear I'm not *testing* this code. But the patches seem extremely clear and I see absolutely nothing wrong with them. If Jeff assures me that the test cases he's run work properly, then I trust him. The code gives me no indication that anything should go wrong here.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
I tried the code locally, and it seems alright. I am gonna give it a try in the morning as well.

**Pull request merged**
