### PR TITLE
JBIDE-26358 New JMX integration tests

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
Green jenkins job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/job/jmx.itests/23

**Comment by odockal** [comment]
@psrna @jkopriva If you could please take a look and review, that would be nice :) Thanks!

**Comment by jkopriva** [comment]
LGTM, does it work? Do you have any test run?

**Comment by odockal** [comment]
@jkopriva  Yes, it is above. @psrna If you do not object anything, or anything is missing here, can we merge?

**Pull request merged**
