### PR TITLE
JBIDE-20367 Fix punctuation for new feature name strings in AS Tools

### PR DESCRIPTION
**Pull request by mmalina**
I'm really sorry that the interactive sed also added new lines at the end
of the file where it was missing. I hope it's ok.

### CODE REVIEW

**Comment by robstryker** [comment]
git reset --soft HEAD~1  # undo the commit
git reset --    # unstage all changed files

git diff --ignore-space-at-eol | grep "diff" | cut -d " " -f 3 | cut -c 3- | awk '{ print "git add " $0;}' | sh   # Only git add the files with whitespace changes

git commit -m "Whatever you want"

**Comment by robstryker** [comment]
Merged after my changes.

**Comment by mmalina** [comment]
I thought having \n at the end of the file is good anyway. But alright. I'm glad you accepted my grammar correction :)

**Comment by mmalina** [comment]
And for the record, I used this:
find . \( -name '*.properties' -or -iname 'MANIFEST.MF' \) -exec sed -i '' 's/, \&/ \&/g' {} \;

**Pull request closed without merging**
