### PR TITLE
Add support for wf19

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by robstryker** [comment]
testPR

**Comment by jeffmaury** [comment]
I recommend to bump versions in micro by 100 so that if we need to release update for the previous release train (2019-12), we have space.
Also you forget to add download for WF19 here: https://github.com/jbosstools/jbosstools-server/blob/master/as/itests/pom.xml#L190

**Comment by robstryker** [comment]
Interesting, never saw that jacoco stuff there.

**Comment by jeffmaury** [comment]
I noticed that WF 19 is now out, can you check the schemas ?

**Comment by jeffmaury** [comment]
testPR

**Pull request merged**
