### PR TITLE
JBIDE-26518 Add org.eclipse.equinox.ds in required bundles for server

### PR DESCRIPTION
**Pull request by jkopriva**
management itests

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
Due to https://bugs.eclipse.org/bugs/show_bug.cgi?id=538737

**Comment by jkopriva** [comment]
Green build: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/server.management.itests/41/jdk=openjdk-1.8,label_exp=rhel7-x64-medium/

**Comment by odockal** [comment]
Further reading: https://help.eclipse.org/2018-12/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Fporting%2Feclipse_4_10_porting_guide.html

**Comment by odockal** [comment]
Seems alright, this issue will require another patch updating bundle for new one (org.apache.felix.scr).

**Comment by jkopriva** [comment]
@odockal I have created another JIRA: https://issues.jboss.org/browse/JBIDE-26519, this is more like a quickfix, JBIDE-26519 will need more investigation.

**Comment by odockal** [comment]
@jkopriva Great, merging.

**Pull request merged**
