### PR TITLE
JBIDE-23785 - wildfly 11 adapter, initial implementation

### PR DESCRIPTION
**Pull request by robstryker**
This PR is incomplete, do not commit.  Just checking for integration failures.

### CODE REVIEW

**Comment by robstryker** [comment]
Sorry sonarqube... I'm not re-writing 10 years of code just to make you smile.

**Comment by mmalina** [comment]
@robstryker , is there a reason why this PR is not targeted for 4.4.x? You only want this for master?

**Comment by mmalina** [comment]
@robstryker also, will there be a separate PR for runtime detection (in base)?

**Comment by mmalina** [comment]
I tried to install this into oxygen m6, but I can't even create any server adapter there - when I open the New Server dialog, I get this immediately:
An error has occurred. See error log for more details.
org.eclipse.wst.server.core.internal.ServerWorkingCopy.newServerDetailsChanged(Lorg/eclipse/core/runtime/IProgressMonitor;)V
And it's thrown again every time I select another server type. And all I can do is cancel the dialog.

So Rob told me he hasn't actually tried this with Oxygen. So I tried to install this into Neon.2 (but I don't feel good about this, because this is in master which is oxygen). I was able to start the server. And then I tried to create a dynamic web project and the new server was not available in the Target Runtime drop down menu. When I closed the dialog, I saw this error:
Version 11.0 of runtime component type org.jboss.ide.eclipse.as.runtime.wildfly.component has not been defined. It is used in plugin org.jboss.ide.eclipse.as.classpath.core.

@robstryker , does it say anything to you?

**Comment by robstryker** [comment]
I created a PR for maintenance with some fixes. I don't believe this will require any changes to runtime detection. Stacks.yaml may require changes but that's it.

**Pull request merged**
