### PR TITLE
JBIDE-22512 - fix test failures for xml catalog tests

### PR DESCRIPTION
**Pull request by robstryker**

### CODE REVIEW

**Comment by fbricon** [comment]
+1

**Comment by mickaelistria** [comment]
testPR

**Comment by alexeykazakov** [comment]
I would rather fix the test somehow and leave this schema in the catalog for now. We should investigate why this schema is not included in WTP. If it's not needed for some reason and XML validator doesn't down load it anyway then let's remove it from our plugin. But if it should be included then we should create a bugzilla for that.

**Comment by alexeykazakov** [comment]
It turned out that this schema was added just a few month ago.
+1 to apply the patch then.

**Pull request merged**
