### PR TITLE
JBIDE-26071 - WildFly 13 server adapter, initial implementation

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by jeffmaury** [comment]
@robstryker worth fixing the sonar issues, at least the last 2 ones

**Comment by mmalina** [comment]
@robstryker , I installed this PR and then started WF13 and then noticed in Console I saw that the LSP server (Camel) was started. So you now use that even in jboss tools? I tried again, but I don't see it in the Console view anymore. But I can see the process with ps:
/usr/bin/java -jar /Users/rasp/jbossqa/devstudio/Eclipse-photon.app/Contents/Eclipse/plugins/com.github.camel-tooling.eclipse.client_1.0.0.201805281102/libs/camel-lsp-server-1.0.0-SNAPSHOT.jar

**Comment by mmalina** [comment]
This is really strange. At some point I saw two camel processes. Then I killed both, started afresh. There was one started after eclipse startup. But then it disappeared. And now I'm no longer seeing it even if I started wildfly 13.
@robstryker can you shed some light on this? What's the expected behavior? When is the server supposed to be running?

**Comment by mmalina** [comment]
OK, so the moment I created a html5 project from central, the server was started and this was displayed in the Console view:
[Info]	Connected to Language Server...
[Info]	Initializing capabilities of the server...

How/why is this used in this case?

**Comment by mmalina** [comment]
Even if I stop Eclipse, the java process is still running. That definitely seems wrong.

**Comment by jeffmaury** [comment]
@mmalina this is not related to @robstryker PR, but rather to this LSP being included into the TP

**Comment by mmalina** [comment]
@jeffmaury ok, I didn't notice it before. I will create a new JIRA for that - I think that at the very least the process should not run when devstudio is shut down.
Otherwise the server adapter for WF13 works fine and can be merged.

**Pull request merged**
