### PR TITLE
JBIDE-26937 Remove Tech Preview from WF12 description

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
My guess is that because we released, that will require a version bump

**Comment by robstryker** [comment]
I was going to add the version change to the patch, but I can't figure out what version this stuff is supposed to be. In fact, when reviewing the poms in the plugin folders, I'm not seeing any .Final recently. 

The most recent change in (for example) as/plugins/org.jboss.ide.eclipse.as.core/pom.xml is a version change back in July from 3.7.0-SNAPSHOT directly to 3.8.0-SNAPSHOT.  So I wonder if this plugin ever had a .final version during the recent release at all?

**Comment by jeffmaury** [comment]
No we never used Final or released version for JBoss Tools so should be bumped to 3.9.0-SNAPSHOT

**Comment by jkopriva** [comment]
@jeffmaury can you please review? Thank you!

**Comment by jkopriva** [comment]
@jeffmaury Thank you!

**Pull request merged**
