### PR TITLE
JBIDE-20667 - new server wizard has 'finish' enabled on first page

### PR DESCRIPTION
**Pull request by robstryker**

### CODE REVIEW

**Comment by fbricon** [comment]
+1 to apply

**Comment by alexeykazakov** [comment]
Any automatic tests?

**Comment by robstryker** [comment]
No automated tests for this, sorry.  Not even sure how to make them.

**Comment by alexeykazakov** [comment]
Open the wizard, check if the Finish button enabled?

**Comment by robstryker** [comment]
1)  Not sure how to get the wizard container's buttons, since it's a protected method
2)  Once I have gotten the buttons, I still need to gain access to the viewer inside a page, so...
3)  I'd need to get access to the wizard page... but.....
4)  The wizard page is actually a TaskWizardPage, wrapping a WizardFragment, and...
5)  The TaskWizardPage has no public API to get the WizardFragment wrapped inside of it
6)  Even if I could somehow get that WizardFragment  (NewServerWizardFragment),  it has no public API to get any of the widgets inside of it (such as the viewer, so I can change selected server type). In fact, inside is just a NewServerComposite, which...
7) also has no API to get its various widgets, including the ServerComposite. The ServerComposite...
8) extends AbstractTreeComposite and has no public API to gain access to the Viewer inside...

So yeah... theoretically I could make the simplest of tests that would just open the new server wizard and verify 'Finish' isn't enabled... but that wouldn't actually be testing anything unless we could also find a way to select each of the various JBT server types nad verify finish is disabled for all of them.  

I'm not sure what we do for tests like this, but I don't imagine we do a lot of reflection and hacking to gain access to the inner fields, do we?

**Comment by alexeykazakov** [comment]
We have a similar test for Seam Wizard - https://github.com/jbosstools/jbosstools-javaee/blob/master/seam/tests/org.jboss.tools.seam.ui.test/src/org/jboss/tools/seam/ui/test/wizard/SeamProjectNewWizardTest.java#L106
But I understand your point if the New Server wizard is even more complected and such test will require a lot of reflection/hacking.

**Comment by maxandersen** [comment]
FYI: if used SWTBot you shouldn't need to access any inner fields, just navigate the buttons/hiearchy by id's.

**Pull request merged**
