### PR TITLE
JBIDE-26545 Update download URL for eap 7

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
File is available on new URL(same md5 checksum).

**Comment by robstryker** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by robstryker** [comment]
Build is failing due to some sonarcloud stuff. I don't know who can look into that, but I'm not familiar with that stuff at all. 

Rest of the build looked good though.

**Pull request merged**
