### PR TITLE
JBIDE-26519 Replace org.eclipse.equinox.ds for org.apache.felix.scr

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
Relevant bugzillas:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538737
https://bugs.eclipse.org/bugs/show_bug.cgi?id=501950

**Comment by robstryker** [comment]
09:39:27 [ERROR] Failed to resolve target definition /mnt/hudson_workspace/workspace/jbosstools-server-Pull-Request/.repository/org/jboss/tools/targetplatforms/jbosstools-unified/4.11.0.AM1-SNAPSHOT/jbosstools-unified-4.11.0.AM1-SNAPSHOT-jbosstools-unified.target: Could not find "com.github.cameltooling.lsp.eclipse.client.feature.feature.group/1.0.0.201810151102" in the repositories of the current location -> [Help 1]
09:39:27 [ERROR] 


Anyone know what's wrong here?

**Comment by odockal** [comment]
@robstryker @jeffmaury How about last changes to TP: https://issues.jboss.org/browse/JBIDE-26477 ?

**Comment by jeffmaury** [comment]
can you respawn the build because it should get the new LSP client now

**Comment by jeffmaury** [comment]
testPR

**Comment by robstryker** [comment]
19:33:15 [ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.2.0:wget (install-eap-7.x) on project org.jboss.tools.as.jmx.ui.bot.itests: IO Error: No space left on device -> [Help 1]
19:33:15 [ERROR] 
19:33:15 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
19:33:15 [ERROR] Re-run Maven using the -X switch to enable full debug logging.

Failed due to OOM.

**Comment by odockal** [comment]
@robstryker Was it run on the same slave? Could killing the slave help?

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
@robstryker @jeffmaury can you please review once again?

**Pull request merged**
