### PR TITLE
Delete .project and .classpath files from repository

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by sbouchet** [comment]
if there is no more .project/.classpath , how contributors can imports the projects under eclipse ? must they use maven/m2e imports ?

**Comment by odockal** [comment]
@sbouchet Is there an issue importing server projects/plugins as Maven Import in Eclipse? I would really appreciate removing these files as they create a lot of mess when making changes using git and I am not sure if there are anywhere else... ? But I might be wrong, though...

**Comment by jkopriva** [comment]
@sbouchet @odockal I would suggest to delete these files, .project and .classpath are automatically created when importing project in Eclipse. I have removed these files from openshift repo with no issues.

Unfortunately I have found some issues in server repo. I am working on fixing it.

**Comment by sbouchet** [comment]
@odockal : no there is no issue when user import as maven import. that was my remark, users/developers are required to use that action, that will create automatically the missing .project/.classpath . if they use basic imports, there will be an issue :)

**Comment by odockal** [comment]
@sbouchet  True that! Thanks for remarks.

**Comment by robstryker** [comment]
Rebased and testing here:  https://github.com/jbosstools/jbosstools-server/pull/695

**Comment by robstryker** [comment]
Closing this issue since the other is rebased.

**Pull request closed without merging**
