### PR TITLE
JBIDE-26644 Sonar coverage fix and removal of .settings folder from repo

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
Should be merged after: jbosstools/jbosstools-build#289

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
@jkopriva : build failed with version check error : 
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:1.4.0:compare-version-with-baselines (default) on project org.jboss.tools.archives.scanner: Only qualifier changed for (org.jboss.tools.archives.scanner/3.6.202.v20191031-1415). Expected to have bigger x.y.z than what is available in baseline (3.6.202.v20181011-1445) -> [Help 1]

**Comment by sbouchet** [comment]
Hi, i can see some warnings about sonarqube :
1 - `[WARNING] Property 'sonar.jacoco.reportPaths' is deprecated (JaCoCo binary format). 'sonar.coverage.jacoco.xmlReportPaths' should be used instead (JaCoCo XML format). Please check that the JaCoCo plugin is installed on your SonarQube Instance.`
2 - The sonarqube result is shown here: https://sonarcloud.io/project/issues?id=org.jboss.tools%3Aserver.all&pullRequest=624&resolved=false&types=CODE_SMELL
and it seems not using the correct organization. can you confirm the analysis will be present here : https://sonarcloud.io/dashboard?id=jbosstools_jbosstools-server ?

**Comment by sbouchet** [comment]
> 2 - The sonarqube result is shown here: https://sonarcloud.io/project/issues?id=org.jboss.tools%3Aserver.all&pullRequest=624&resolved=false&types=CODE_SMELL
> and it seems not using the correct organization. can you confirm the analysis will be present here : https://sonarcloud.io/dashboard?id=jbosstools_jbosstools-server ?
Find out that the Pull Request build configuration on Jenkins is using: 
```
-Dsonar.host.url=https://sonarcloud.io
-Dsonar.organization=default
```
Maybe change organization to 'jbosstools' should be enough.

**Comment by sbouchet** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
We can fine tune coverage reports in next PRs.

**Comment by jkopriva** [comment]
@sbouchet Thank you!

**Pull request merged**
