### PR TITLE
JBIDE-27711 Variable updates in ITests

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
testPR

**Review by odockal — APPROVED** [review]

**Comment by robstryker** [comment]
@jkopriva  I've pushed the eap 7.4 PR as well, so this patch may need further updates.

**Comment by jkopriva** [comment]
@odockal please rereview it, I have updated tests for EAP 7.4. Thank you!

**Comment by robstryker** [comment]
I've opened https://github.com/jbosstools/jbosstools-server/issues/714  to have this part of the script since I obviously keep missing this part. Sorry guys.

**Review by odockal — APPROVED** [review]

**Pull request merged**
