### PR TITLE
Fixing MANIFEST.MF file for tests to run

### PR DESCRIPTION
**Pull request by lgrossma**
Signed-off-by: Lukas Grossmann <lgrossma@redhat.com>

### CODE REVIEW

**Comment by lgrossma** [comment]
@odockal could you check please?

**Comment by odockal** [comment]
@lgrossma LGTM. Can you please check also on Jenkins if the build and tests are working? thx.

**Comment by lgrossma** [comment]
Screenshot 2022-09-12 at 14 04 42

**Comment by odockal** [comment]
@lgrossma That is not particularly convincing :) How should I read it?

**Pull request merged**
