### PR TITLE
JBIDE-19641 - Upgrade wf jars to wf9, force as71 and above to use those wf jars

### PR DESCRIPTION
**Pull request by robstryker**
The wildfly 9 jars seem to work with all previous versions down to 7.1.x.  Unfortunately, as7.0.x doesn't work with the wf9 jars.

### CODE REVIEW

**Comment by robstryker** [comment]
PR is incomplete:  missing increased timeout logic for as71x

**Comment by robstryker** [comment]
So it seems the as7 management plugin still has actual jars in the folder, while the wf8 plugin uses the proper fetching in pom.xml.  

I've spent some time looking into converting the as7 management plugin to use the same style of fetching, however, since it has EAP jars in it, not all the jars are publicly available.  There are jars with the same version (ie dmr 1.1.6)  but they have different md5 sums, and I don't think it's safe to change those over and introduce a new set of jars.

**Comment by robstryker** [comment]
A grep on teiid shows no deps aside from feature deps, which is fine.  

A grep on fuseide repo shows the fuseide/targetplatform/*.launch files reference the plugin directly.

**Comment by maxandersen** [comment]
if the jars are not publically available we should not be using them.

do we not have enough proper tests to ensure we can upgrade these ?

**Comment by robstryker** [comment]
> if the jars are not publically available we should not be using them.

I've switched the out and all unit tests pass.  Most of the jars were available in the tech-preview nexus site. One or two needed minor changes / updates to slightly different version strings  (-redhat-8 instead of -redhat-4), but all tests still pass. 

I think this patch is ready to be committed. Would like a review.

**Comment by maxandersen** [comment]
what is tech-preview nexus site ? there are no such thing publicly available afaik, only behind vpn.

**Pull request merged**
