### PR TITLE
Clean code during investigation on FUSETOOLS-2361

### PR DESCRIPTION
**Pull request by apupier**
- fix warning
- replace deprecated usage of SubProgressMonitor
- improved progress reporting accuracy

### CODE REVIEW

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
I don't see any link of th failign test with my PR:

Error Message

expected:<0> but was:<1>

Stacktrace

junit.framework.AssertionFailedError: expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at junit.framework.TestCase.assertEquals(TestCase.java:409)
	at org.jboss.tools.as.test.core.classpath.modules.JBossModulesClasspathTest.testManifestVersionAdditions(JBossModulesClasspathTest.java:228)

**Comment by apupier** [comment]
testPR

**Comment by robstryker** [comment]
merged after rebase

**Pull request closed without merging**
