### PR TITLE
[JBIDE-22642] Support search of JPS executable path on Windows

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by robstryker** [comment]
Thanks for the patch, @apupier !   I'll look into ti shortly.  Did you test it, and does it work?  :)

**Comment by apupier** [comment]
There is no more exceptions thrown but I'm not sure what was the final purpose of this.

**Comment by jeffmaury** [comment]
testPR

**Comment by apupier** [comment]
all failing tests seems to have nothing to do with my PR

**Comment by robstryker** [comment]
This class is not present in master, and we will not be updating 4.3.x any further.

**Pull request closed without merging**
