### PR TITLE
JBIDE-17022 - New implementation for managing output of RSE servers, …

### PR DESCRIPTION
**Pull request by robstryker**
…improve mocked process

This needs to be tested a bit more thoroughly before commit. @mmalina  your turn ;)

### CODE REVIEW

**Comment by mmalina** [comment]
@robstryker , so what exactly does this achieve? What should I check other that nothing breaks? Should Show In Console work now?

**Comment by robstryker** [comment]
Need to test all output goes into console, no munging of data (ie lines out of order or half-complete lines), buffer flushes at end when expected, and show in console works.

**Comment by mmalina** [comment]
It seems to work correctly for me. Here's an example of the output:
`Last login: Wed Oct  5 09:26:46 2016 from nattura.brq.redhat.com
cd /

cd /

echo $PWD'>'
echo $PWD'>'
java "-Dprogram.name=JBossTools: Red Hat JBoss EAP 7.0 marvin" -server -Xms64m -Xmx512m -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true "-Dorg.jboss.boot.log.file=/home/rasp/jbossqa/runtimes/jboss-eap-7.0/standalone/log/boot.log" "-Dlogging.configuration=file:/home/rasp/jbossqa/runtimes/jboss-eap-7.0/standalone/configuration/logging.properties" "-Djboss.home.dir=/home/rasp/jbossqa/runtimes/jboss-eap-7.0" -Dorg.jboss.logmanager.nocolor=true -Djboss.bind.address.management=MARVIN -jar /home/rasp/jbossqa/runtimes/jboss-eap-7.0/jboss-modules.jar -mp "/home/rasp/jbossqa/runtimes/jboss-eap-7.0/modules" org.jboss.as.standalone -b 0.0.0.0 --server-config=standalone.xml -Djboss.server.base.dir=/home/rasp/jbossqa/runtimes/jboss-eap-7.0/standalone&
echo "JBTOOLS_SERVER_START_CMD:Red Hat JBoss EAP 7.0 marvin:"$!
[rasp@marvin ~]$ cd /
[rasp@marvin /]$ 
[rasp@marvin /]$ cd /
[rasp@marvin /]$ 
[rasp@marvin /]$ echo $PWD'>'
/>
[rasp@marvin /]$ echo $PWD'>'
/>
[rasp@marvin /]$ java "-Dprogram.name=JBossTools: Red Hat JBoss EAP 7.0 marvin"  -server -Xms64m -Xmx512m -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4 Stack=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterv al=3600000 -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=tru e "-Dorg.jboss.boot.log.file=/home/rasp/jbossqa/runtimes/jboss-eap-7.0/standalon e/log/boot.log" "-Dlogging.configuration=file:/home/rasp/jbossqa/runtimes/jboss- eap-7.0/standalone/configuration/logging.properties" "-Djboss.home.dir=/home/ras p/jbossqa/runtimes/jboss-eap-7.0" -Dorg.jboss.logmanager.nocolor=true -Djboss.bi nd.address.management=MARVIN -jar /home/rasp/jbossqa/runtimes/jboss-eap-7.0/jbos s-modules.jar -mp "/home/rasp/jbossqa/runtimes/jboss-eap-7.0/modules" org.jboss. as.standalone -b 0.0.0.0 --server-config=standalone.xml -Djboss.server.base.dir= /home/rasp/jbossqa/runtimes/jboss-eap-7.0/standalone&
[1] 22908
[rasp@marvin /]$ echo "JBTOOLS_SERVER_START_CMD:Red Hat JBoss EAP 7.0 marvin:"$! !
JBTOOLS_SERVER_START_CMD:Red Hat JBoss EAP 7.0 marvin:22908
[rasp@marvin /]$ 
wait 22908; echo "JBTOOLS_SERVER_LAUNCH_TERMINATED_CMD:Red Hat  JBoss EAP 7.0 marvin:" $?
09:27:13,360 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.1.Final-redhat-1
09:27:13,738 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final-redhat-1
09:27:13,848 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: JBoss EAP 7.0.0.GA (WildFly Core 2.1.2.Final-redhat-1) starting
09:27:15,532 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
09:27:15,552 INFO  [org.xnio] (MSC service thread 1-2) XNIO version 3.3.6.Final-redhat-1
09:27:15,557 INFO  [org.xnio.nio] (MSC service thread 1-2) XNIO NIO Implementation Version 3.3.6.Final-redhat-1
09:27:15,588 INFO  [org.jboss.remoting] (MSC service thread 1-2) JBoss Remoting version 4.0.18.Final-redhat-1
09:27:15,666 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 37) WFLYIO001: Worker 'default' has auto-configured to 4 core threads with 32 task threads based on your 2 available processors
09:27:15,703 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 38) WFLYCLINF0001: Activating Infinispan subsystem.
09:27:15,730 INFO  [org.jboss.as.connector] (MSC service thread 1-4) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.3.3.Final-redhat-1)
09:27:15,761 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 33) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
09:27:15,763 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) WFLYJCA0018: Started Driver service with driver-name = h2
09:27:15,790 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 56) WFLYWS0002: Activating WebServices Extension
09:27:15,795 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 54) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
09:27:15,815 INFO  [org.jboss.as.jsf] (ServerService Thread Pool -- 44) WFLYJSF0007: Activated the following JSF Implementations: [main]
09:27:15,985 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 53) WFLYSEC0002: Activating Security Subsystem
09:27:16,044 INFO  [org.jboss.as.security] (MSC service thread 1-4) WFLYSEC0001: Current PicketBox version=4.9.6.Final-redhat-1
09:27:16,052 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 55) WFLYUT0003: Undertow 1.3.21.Final-redhat-1 starting
09:27:16,054 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0003: Undertow 1.3.21.Final-redhat-1 starting
09:27:16,145 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 46) WFLYNAM0001: Activating Naming Subsystem
09:27:16,154 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 55) WFLYUT0014: Creating file handler for path '/home/rasp/jbossqa/runtimes/jboss-eap-7.0/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
09:27:16,225 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0012: Started server default-server.
09:27:16,265 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0018: Host default-host starting
09:27:16,295 INFO  [org.jboss.as.naming] (MSC service thread 1-1) WFLYNAM0003: Starting Naming Service
09:27:16,297 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-1) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
09:27:16,407 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0006: Undertow HTTP listener default listening on 0.0.0.0:8080
09:27:16,436 INFO  [org.jboss.as.ejb3] (MSC service thread 1-4) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 8 (per class), which is derived from the number of CPUs on this host.
09:27:16,440 INFO  [org.jboss.as.ejb3] (MSC service thread 1-3) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 32 (per class), which is derived from thread worker pool sizing.
09:27:16,659 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
09:27:17,071 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-1) ISPN000128: Infinispan version: Infinispan 'Mahou' 8.1.2.Final-redhat-1
09:27:17,110 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-1) WFLYDS0013: Started FileSystemDeploymentService for directory /home/rasp/jbossqa/runtimes/jboss-eap-7.0/standalone/deployments
09:27:17,217 INFO  [org.jboss.ws.common.management] (MSC service thread 1-2) JBWS022052: Starting JBossWS 5.1.3.SP1-redhat-1 (Apache CXF 3.1.4.redhat-1) 
09:27:17,435 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://10.34.40.182:9990/management
09:27:17,436 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://10.34.40.182:9990
09:27:17,436 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: JBoss EAP 7.0.0.GA (WildFly Core 2.1.2.Final-redhat-1) started in 4571ms - Started 267 of 553 services (371 services are lazy, passive or on-demand)
`

**Comment by mmalina** [comment]
One small thing I noticed is that if I close the Console view and then use Show in console, it will take me to the beginning of the log, not the end as I would have expected. But I don't really see that as a big issue. You might even say it's intended ;)

**Pull request merged**
