### PR TITLE
JBIDE-24280 - provide correct Java types for Jolokia request

### PR DESCRIPTION
**Pull request by apupier**
- partial implementation: only int and Date are implemented
- will require to write more tests for other types and for invocation
method

Not sure when i will have time to continue working on it but this block is making meaning so feedback is welcome at this stage.
i think that as soon as the tests for invoke method is written this can be merged and further work can be done in a separate PR.

### CODE REVIEW

**Comment by apupier** [comment]
I think that the reported Sonar issue is a false positive, I don't have any instanceof the corresponding type at that time

**Comment by apupier** [comment]
The 6 issue reported by SonarQube are false-positive, no instances are available to do the comparison, we are retrieving Strings  from Jolokia through http.

**Comment by apupier** [comment]
Ready for review

**Comment by robstryker** [comment]
Merged after a rebase. Closing manually.

**Pull request closed without merging**
