### PR TITLE
JBIDE-26554 Add WildFly 15 in ITests suites

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
Green build: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/server.it.weekly.jkopriva/jdk=jdk11,label_exp=fedora29/425/testReport/org.jboss.tools.as.ui.bot.itests.parametized.server/ServerRuntimesTest/

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by odockal** [comment]
Jenkins job has executed new wilfdly 15 server test. It has passed from linked job, I am giving this PR +1.

**Pull request merged**
