### PR TITLE
Refactor itests to use RedDeer2

### PR DESCRIPTION
**Pull request by rawagner**
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by robstryker** [comment]
Hey @rawagner  - I can't merge this because it won't build. Are changes needed to TP first?

**Comment by rawagner** [comment]
@robstryker you are correct. We need to wait for TP 4.71 and also https://github.com/jbosstools/jbosstools-base/pull/593 needs to be merged (also depends on TP 4.71).

**Comment by psrna** [comment]
testPR

**Comment by nickboldt** [comment]
testPR

**Pull request merged**
