### PR TITLE
Add missing headers

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by sbouchet** [comment]
@robstryker the header are incorrectly formatted, please use this one? 
```
/*******************************************************************************
 * Copyright (c) 2020 Red Hat, Inc.
 * Distributed under license by Red Hat, Inc. All rights reserved.
 * This program is made available under the terms of the
 * Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Red Hat, Inc. - initial API and implementation
 ******************************************************************************/
```

**Comment by jeffmaury** [comment]
EPL 1 is deprecated, we should use EPL 2 now

**Comment by robstryker** [comment]
I remade the patch. It's still using epl2 (not deprecated). It made the lines more similar to Stephane's, but I did not add "Initial API and implementation" because, when updating tons of old files, it's too much work to actually verify all the files you're slapping your header on were actually made by you originally. So listing ourselves as a contributor is safer. 

Let's not bikeshed this ;)  Just push it =P

**Comment by robstryker** [comment]
testPR

**Comment by robstryker** [comment]
testPR

**Pull request merged**
