### PR TITLE
[JBIDE-25855] add org.jboss.tools.openshift.core as friend

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@robstryker please review

**Comment by adietish** [comment]
@robstryker please review

**Comment by robstryker** [comment]
Isn't it more reasonable to make this class API?

**Comment by adietish** [comment]
@robstryker +1 for making this API

**Comment by robstryker** [comment]
You can use these classes / subsystems without extending them. Most of the others probably aren't designed for subclassing and haven't been tested as thoroughly.  So I'm not in any hurry to make them API until someone claims they need it.

**Comment by adietish** [comment]
dropping this in favor of https://github.com/jbosstools/jbosstools-server/pull/568

**Pull request closed without merging**
